---

- hosts: all
  become: true
  tasks:

  - name: Update repository index
    apt:
      update_cache: yes

  - name: Delete  apache2 package
    apt:
      name: apache2
      state: absent

  - name: Delete php support for apache
    apt:
      name: libapache2-mod-php
      state: remove

